{
 "title": "SNMP Exporter Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(snmp_exporter_build_info,instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(snmp_scrape_duration_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packets total",
   "type": "timeseries",
   "description": "Number of SNMP packet sent, including retries.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(snmp_packets_total{instance=\"$instance\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets retries total",
   "type": "timeseries",
   "description": "Number of SNMP packet retries.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(snmp_packet_retries_total{instance=\"$instance\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request error total",
   "type": "timeseries",
   "description": "Errors in requests to the SNMP exporter",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(snmp_request_errors_total{instance=\"$instance\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request in-flight",
   "type": "timeseries",
   "description": "Current number of SNMP scrapes being requested.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(snmp_request_in_flight{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet duration seconds bucket",
   "type": "heatmap",
   "description": "Cumulative counters for the observation buckets (A histogram of latencies for SNMP packets.)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by(le) (rate(snmp_packet_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collection duration seconds bucket",
   "type": "heatmap",
   "description": "Cumulative counters for the observation buckets (Duration of collections by the SNMP exporter)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum by(le) (rate(snmp_collection_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNMP Exporter Build Info",
   "type": "table",
   "description": "A metric with a constant '1' value labeled by version, revision, branch, goversion from which snmp_exporter was built, and the goos and goarch for the build",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "snmp_exporter_build_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device: $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "device" },
  {
   "title": "Scrape duration (s)",
   "type": "timeseries",
   "description": "Total SNMP time scrape took (walk and processing).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{instance=~\"$device\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Scrape walk duration (s)",
   "type": "timeseries",
   "description": "Time SNMP walk/bulkwalk took.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_walk_duration_seconds{instance=~\"$device\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Packets sent",
   "type": "timeseries",
   "description": "Packets sent for get, bulkget, and walk; including retries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_scrape_packets_sent{instance=~\"$device\"} - snmp_scrape_packets_retried{instance=~\"$device\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Packets retried",
   "type": "timeseries",
   "description": "Packets retried for get, bulkget, and walk.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_scrape_packets_retried{instance=~\"$device\"}",
     "legendFormat": "{{module}}"
    }
   ]
  }
 ]
}