{
 "title": "Docker / Engine",
 "tags": [ "docker-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(engine_daemon_engine_info,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(engine_daemon_engine_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job)(go_goroutines{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job)(go_threads{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "gc memstats heap inuse",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "released"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Docker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "os",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "os_version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{os_version}}"
    }
   ]
  },
  {
   "title": "kernel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kernel}}"
    }
   ]
  },
  {
   "title": "NOTE",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "options": {
    "content": "To configure the Docker daemon as a Prometheus target, you need to specify the `metrics-address` in the `daemon.json` configuration file.\n\n```json\n{\n  \"metrics-addr\": \"127.0.0.1:9323\"\n}\n```\n\nSee https://docs.docker.com/engine/daemon/prometheus/#configure-the-daemon."
   }
  },
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "graphdriver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{graphdriver}}"
    }
   ]
  },
  {
   "title": "architecture",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{architecture}}"
    }
   ]
  },
  { "title": "Docker Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_states_containers",
   "type": "state-timeline",
   "description": "The number of tasks in the cluster object store",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_actions_seconds_sum",
   "type": "heatmap",
   "description": "The number of seconds it takes to process each container action",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(engine_daemon_container_actions_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "engine_daemon_network_actions_seconds_sum",
   "type": "heatmap",
   "description": "The number of seconds it takes to process each network action",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(engine_daemon_network_actions_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "engine_daemon_image_actions_seconds_sum",
   "type": "heatmap",
   "description": "The number of seconds it takes to process each image action",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(engine_daemon_image_actions_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "engine_daemon_host_info_functions_seconds_sum",
   "type": "heatmap",
   "description": "The number of seconds it takes to call functions gathering info about the host",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(engine_daemon_host_info_functions_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "engine_daemon_events_subscribers_total",
   "type": "timeseries",
   "description": "The number of current subscribers to events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_events_subscribers_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "subscribers"
    }
   ]
  },
  {
   "title": "engine_daemon_events_total",
   "type": "timeseries",
   "description": "The number of events logged",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_events_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Docker Engine - Container Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "engine_daemon_container_actions_seconds_bucket{action=\"create\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_container_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"create\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_actions_seconds_bucket{action=\"start\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_container_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"start\"}[$__rate_interval]))",
     "legendFormat": "{{let}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_actions_seconds_bucket{action=\"delete\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_container_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"delete\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_actions_seconds_bucket{action=\"changes\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_container_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"changes\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_actions_seconds_bucket{action=\"commit\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_container_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"commit\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Docker Engine - Image Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "engine_daemon_image_actions_seconds_bucket{action=\"pull\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_image_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"pull\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_image_actions_seconds_bucket{action=\"push\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_image_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"push\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_image_actions_seconds_bucket{action=\"delete\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_image_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"delete\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_image_actions_seconds_bucket{action=\"history\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_image_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"history\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Docker Engine - Network Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 }
  },
  {
   "title": "engine_daemon_network_actions_seconds_bucket{action=\"allocate\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_network_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"allocate\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_network_actions_seconds_bucket{action=\"connect\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_network_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"connect\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_network_actions_seconds_bucket{action=\"update\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_network_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"update\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_network_actions_seconds_bucket{action=\"release\"}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_network_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\", action=\"release\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Docker Engine - Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "engine_daemon_health_check_start_duration_seconds_bucket",
   "type": "heatmap",
   "description": "The number of seconds it takes to prepare to run health checks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(engine_daemon_health_check_start_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "engine_daemon_health_checks",
   "type": "timeseries",
   "description": "The number of health checks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(rate(engine_daemon_health_checks_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "health_checks"
    },
    {
     "expr": "sum(rate(engine_daemon_health_checks_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "health_checks_failed"
    }
   ]
  }
 ]
}