{
 "title": "cAdvisor Exporter Full",
 "tags": [ "cadvisor" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(cadvisor_version_info,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cadvisor_version_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) / scalar(count(count(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel space"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) / scalar(count(count(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in application space"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "Used - Memory used by containers"
    },
    {
     "expr": "sum(container_memory_cache{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "Cache - Memory Cache"
    },
    {
     "expr": "sum(container_memory_swap{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "sum(container_memory_rss{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "RSS - Resident Set Size"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name) / scalar(count(count(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=\"\"})))",
     "legendFormat": "Usage - {{name}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name) / scalar(count(count(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=\"\"})))",
     "legendFormat": "System - {{name}}"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name) / scalar(count(count(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=\"\"})))",
     "legendFormat": "User - {{name}}"
    }
   ]
  },
  { "title": "Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "Used - Memory used by containers"
    },
    {
     "expr": "sum(container_memory_cache{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "Cache - Memory Cache"
    },
    {
     "expr": "sum(container_memory_swap{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "sum(container_memory_rss{job=~\"$job\", instance=~\"$instance\", name=~\".+\"})",
     "legendFormat": "RSS - Resident Set Size"
    },
    {
     "expr": "container_spec_memory_limit_bytes{job=~\"$job\", instance=~\"$instance\", name=\"\"}",
     "legendFormat": "SpecMemLimit - Max allowable memory"
    }
   ]
  },
  {
   "title": "Memory Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(container_memory_failures_total{job=~\"$job\", instance=~\"$instance\", failure_type=\"pgfault\"}[$__rate_interval]))",
     "legendFormat": "Pgfault - Page major and minor fault ops"
    },
    {
     "expr": "sum(irate(container_memory_failures_total{job=~\"$job\", instance=~\"$instance\", failure_type=\"pgmajfault\"}[$__rate_interval]))",
     "legendFormat": "Pgmajfault - Major page fault ops"
    },
    {
     "expr": "sum(irate(container_memory_failures_total{job=~\"$job\", instance=~\"$instance\", failure_type=\"pgfault\"}[$__rate_interval])) - sum(irate(container_memory_failures_total{job=~\"$job\", instance=~\"$instance\", failure_type=\"pgmajfault\"}[$__rate_interval]))",
     "legendFormat": "Pgminfault - Minor page fault ops"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}) by (name)",
     "legendFormat": "Used - {{name}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_cache{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}) by (name)",
     "legendFormat": "Cache - {{name}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name) * 8",
     "legendFormat": "Rx - {{name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name) * 8",
     "legendFormat": "Tx - {{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Rx - {{name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Tx - {{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Rx - {{name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Tx - {{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Rx - {{name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Tx - {{name}}"
    }
   ]
  },
  { "title": "Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Disk Read/Write IOps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Read - {{name}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Write - {{name}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Read - {{name}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Write - {{name}}"
    }
   ]
  },
  {
   "title": "Disk R/W Merged",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_merged_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Read - {{name}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_merged_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Write - {{name}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_read_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval]) / irate(container_fs_reads_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Read - {{name}}"
    },
    {
     "expr": "sum(irate(container_fs_write_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval]) / irate(container_fs_writes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Write - {{name}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Sector",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_sector_reads_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Read - {{name}}"
    },
    {
     "expr": "sum(irate(container_fs_sector_writes_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Write - {{name}}"
    }
   ]
  },
  {
   "title": "Average Queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_io_time_weighted_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "Queue - {{name}}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_io_time_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "General IO - {{name}}"
    }
   ]
  },
  { "title": "cAdvisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cadvisor_build_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cadvisor_build_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{revision}}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cadvisor_version_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{osVersion}}"
    }
   ]
  },
  {
   "title": "OS Kernel Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cadvisor_version_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kernelVersion}}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "(time() - max(container_start_time_seconds{job=~\"$job\", instance=~\"$instance\", name=~\".+\"}) by (name, image, container_label_com_docker_compose_project, container_label_com_docker_stack_namespace))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}