{
 "title": "Docker Engine",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(engine_daemon_engine_info,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(engine_daemon_engine_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job)(go_goroutines{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job)(go_threads{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "gc memstats heap inuse",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "released"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Docker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "os",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "os_version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{os_version}}"
    }
   ]
  },
  {
   "title": "kernel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kernel}}"
    }
   ]
  },
  {
   "title": "NOTE",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "options": {
    "content": "To configure the Docker daemon as a Prometheus target, you need to specify the `metrics-address` in the `daemon.json` configuration file.\n\n```json\n{\n  \"metrics-addr\": \"127.0.0.1:9323\"\n}\n```\n\nSee https://docs.docker.com/engine/daemon/prometheus/#configure-the-daemon."
   }
  },
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "graphdriver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{graphdriver}}"
    }
   ]
  },
  {
   "title": "architecture",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{architecture}}"
    }
   ]
  },
  { "title": "Docker Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_states_containers",
   "type": "state-timeline",
   "description": "The number of tasks in the cluster object store",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "engine_daemon_container_actions_seconds_bucket",
   "type": "heatmap",
   "description": "The number of seconds it takes to process each container action",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(engine_daemon_container_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, action))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_daemon_network_actions_seconds_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(engine_daemon_network_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, action))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_daemon_image_actions_seconds_bucket",
   "type": "heatmap",
   "description": "The number of seconds it takes to process each image action",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(engine_daemon_image_actions_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, action))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_daemon_host_info_functions_seconds_bucket",
   "type": "heatmap",
   "description": "The number of seconds it takes to call functions gathering info about the host",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(engine_daemon_host_info_functions_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, function))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_daemon_events_subscribers_total",
   "type": "timeseries",
   "description": "The number of current subscribers to events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_events_subscribers_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "subscribers"
    }
   ]
  },
  {
   "title": "engine_daemon_health_check_start_duration_seconds_bucket",
   "type": "heatmap",
   "description": "The number of seconds it takes to prepare to run health checks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (increase(engine_daemon_health_check_start_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "engine_daemon_events_total",
   "type": "timeseries",
   "description": "The number of events logged",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_events_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "engine_daemon_health_checks",
   "type": "timeseries",
   "description": "The number of health checks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_health_checks_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "health_checks"
    },
    {
     "expr": "sum(rate(engine_daemon_health_checks_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "health_checks_failed"
    }
   ]
  },
  {
   "title": "Docker Swarm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "swarm_manager_nodes",
     "type": "state-timeline",
     "description": "The number of nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "swarm_manager_nodes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "swarm_manager_tasks_total",
     "type": "state-timeline",
     "description": "The number of tasks in the cluster object store",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "swarm_manager_tasks_total{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "swarm_manager_services_total",
     "type": "timeseries",
     "description": "The number of services in the cluster object store",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum(swarm_manager_services_total{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "swarm_manager_configs_total",
     "type": "timeseries",
     "description": "The number of configs in the cluster object store",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "swarm_manager_configs_total{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "swarm_manager_tasks_total",
     "type": "timeseries",
     "description": "The number of tasks in the cluster object store",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "swarm_manager_tasks_total{job=~\"$job\", instance=~\"$instance\", state=\"running\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "swarm_manager_secrets_total",
     "type": "timeseries",
     "description": "The number of secrets in the cluster object store",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "swarm_manager_secrets_total{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "swarm_dispatcher_scheduling_delay_seconds_bucket",
     "type": "heatmap",
     "description": "Scheduling delay is the time a task takes to go from NEW to RUNNING state.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_dispatcher_scheduling_delay_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_raft_transaction_latency_seconds_bucket",
     "type": "heatmap",
     "description": "Raft transaction latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_raft_transaction_latency_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_store_batch_latency_seconds_bucket",
     "type": "heatmap",
     "description": "Raft store batch latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_store_batch_latency_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_store_lookup_latency_seconds_bucket",
     "type": "heatmap",
     "description": "Raft store read latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_store_lookup_latency_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_store_read_tx_latency_seconds_bucket",
     "type": "heatmap",
     "description": "Raft store read tx latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_store_read_tx_latency_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_store_write_tx_latency_seconds_bucket",
     "type": "heatmap",
     "description": "Raft store write tx latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_store_write_tx_latency_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_store_memory_store_lock_duration_seconds_bucket",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_store_memory_store_lock_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "swarm_raft_snapshot_latency_seconds_bucket",
     "type": "heatmap",
     "description": "Raft snapshot create latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(swarm_raft_snapshot_latency_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker Swarm (etcd)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "etcd_snap_fsync_duration_seconds_bucket",
     "type": "heatmap",
     "description": "The latency distributions of fsync called by snap.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(etcd_snap_fsync_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "etcd_snap_db_fsync_duration_seconds_bucket",
     "type": "heatmap",
     "description": "The latency distributions of fsyncing .snap.db file",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(etcd_snap_db_fsync_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "etcd_snap_db_save_total_duration_seconds_bucket",
     "type": "heatmap",
     "description": "The total latency distributions of v3 snapshot save",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(etcd_snap_db_save_total_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "etcd_disk_wal_fsync_duration_seconds_bucket",
     "type": "heatmap",
     "description": "The latency distributions of fsync called by WAL.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "etcd_disk_wal_write_duration_seconds_bucket",
     "type": "heatmap",
     "description": "The latency distributions of write called by WAL.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (increase(etcd_disk_wal_write_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  }
 ]
}